// <auto-generated />
using System;
using Infrastructure.Data.Interface;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(TestTeckDbContext))]
    [Migration("20211228170819_gh")]
    partial class gh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Amortissement", b =>
                {
                    b.Property<int>("AmortissementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CapitaleRembourse")
                        .HasColumnType("float");

                    b.Property<int?>("FirstResultsId")
                        .HasColumnType("int");

                    b.Property<double>("Interet")
                        .HasColumnType("float");

                    b.Property<double>("Mensualite")
                        .HasColumnType("float");

                    b.Property<int>("Periode")
                        .HasColumnType("int");

                    b.Property<double>("SoldeDebut")
                        .HasColumnType("float");

                    b.Property<double>("SoldeFin")
                        .HasColumnType("float");

                    b.HasKey("AmortissementId");

                    b.HasIndex("FirstResultsId");

                    b.ToTable("Amortissement");
                });

            modelBuilder.Entity("Domain.FirstResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Capital")
                        .HasColumnType("float");

                    b.Property<double>("FondPropre")
                        .HasColumnType("float");

                    b.Property<double>("FraisDachat")
                        .HasColumnType("float");

                    b.Property<double>("FraisDhypotheque")
                        .HasColumnType("float");

                    b.Property<double>("InteretAnnuel")
                        .HasColumnType("float");

                    b.Property<double>("InteretMensuel")
                        .HasColumnType("float");

                    b.Property<double>("Mensualite")
                        .HasColumnType("float");

                    b.Property<double>("MentantEmpBrut")
                        .HasColumnType("float");

                    b.Property<double>("MentantEmpNet")
                        .HasColumnType("float");

                    b.Property<double>("MontantDachat")
                        .HasColumnType("float");

                    b.Property<int>("duree")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("results");
                });

            modelBuilder.Entity("Domain.Amortissement", b =>
                {
                    b.HasOne("Domain.FirstResults", null)
                        .WithMany("Amortissements")
                        .HasForeignKey("FirstResultsId");
                });
#pragma warning restore 612, 618
        }
    }
}
