// <auto-generated />
using Infrastructure.Data.Interface;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(TestTeckDbContext))]
    [Migration("20211227022730_d")]
    partial class d
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.FirstResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("FondPropre")
                        .HasColumnType("float");

                    b.Property<double>("FraisDachat")
                        .HasColumnType("float");

                    b.Property<double>("FraisDhypotheque")
                        .HasColumnType("float");

                    b.Property<double>("Mensualite")
                        .HasColumnType("float");

                    b.Property<double>("MentantEmpBrut")
                        .HasColumnType("float");

                    b.Property<double>("MentantEmpNet")
                        .HasColumnType("float");

                    b.Property<double>("MontantDachat")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("results");
                });
#pragma warning restore 612, 618
        }
    }
}
